# Might want to consider using tag or commit.
frontend:
  aeolus_fe:
    scm:
      scm_repo_branch: release-aeolus-2.60.1
  fe_prep:
    scm:
      scm_repo_branch: release-2.60.0
#  vscreen:
#    scm:
#      scm_repo_branch: release-2.56.1
#  queryeditor:
#    scm:
#      scm_repo_branch: release-qe-2.59.1
#  aeolus_h5:
#    scm:
#      scm_repo_branch: release-aeolus-2.56.1
backend:
  aeolus:
    scm:
      scm_repo_branch: euttp_2.60.1
  prepare:
    scm:
      scm_repo_branch: release-aeolus-2.60.0
  meta_service:
    scm:
      scm_repo_branch: release-aeolus-2.60.0
  vqs:
    scm:
      scm_repo_branch: release-aeolus-2.60.0
  bdb_backend:
    scm:
      scm_repo_branch: release-1.3.0
  bdb_jobserver:
    scm:
      scm_repo_branch: release-1.3.0
  bdb_scheduler:
    scm:
      scm_repo_branch: release-1.3.0
  ars:
    scm:
      scm_repo_branch: release-aeolus-2.60.0
  aeolus_glue:
    scm:
      scm_repo_branch: release-aeolus-2.60.1
  # Currently no gray
#  eventhub:
#    scm:
#      scm_repo_branch: release-aeolus-2.51.0
#  ajs:
#    scm:
#      scm_repo_branch: 0616-feat_eu_ttp_deploy__0427
#  subscription:
#    scm:
#      scm_repo_branch: release-aeolus-2.56.1
#  subscription_push_script:
#    scm:
#      scm_repo_branch: release-aeolus-2.56.1
#  notification:
#    scm:
#      scm_repo_branch: fix-eu-ttp-mesh-2.56.1
#  sqlquery:
#    scm:
#      scm_repo_branch: skydorm-debug

#data/dp/aeolus_fe_eu_ttp: release-aeolus-2.60.1
#data/dp/fe_prep_eu_ttp: release-2.60.0
#data/dp/vscreen: release-2.56.1
#data/dp/aeolus_query_editor_v2_eu_ttp: release-qe-2.59.1
#data/dp/aeolus_h5_eu_ttp: release-aeolus-2.56.1
#data/dp/aeolus: euttp_2.60.1
#dp/aeolus/aeolus_prep: release-aeolus-2.60.0
#dp/aeolus/metaservice: release-aeolus-2.60.0
#data/dp/vqs: release-aeolus-2.60.0
#dp/bigdatabase/all: release-1.3.0
#data/dp/aeolus_resource_service: release-aeolus-2.60.0
#dp/aeolus_fe/glue: release-aeolus-2.60.1
## Currently no gray
#data/dp/eventhub: release-aeolus-2.51.0
#data/dp/aeolus_job_scheduler: 0616-feat_eu_ttp_deploy__0427
#data/dp/subscription: release-aeolus-2.56.1
#data/dp/notification: fix-eu-ttp-mesh-2.56.1
#data/dp/sqlquery: skydorm-debug